# frozen_string_literal: true

# This file was generated by https://github.com/salami/salami/blob/master/.github/workflows/release_packages.yml
class Salami < Formula
  desc "Salami - Infrastructure as Natural Language"
  homepage "https://github.com/petrgazarov/salami"
  version ""
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url ""
      sha256 ""
    end

    if Hardware::CPU.arm?
      url ""
      sha256 ""
    end

    def install
      if Hardware::CPU.intel?
        filename = File.basename("")
        bin.install filename => "salami"
      end

      if Hardware::CPU.arm?
        filename = File.basename("")
        bin.install filename => "salami"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url ""
      sha256 ""
    end

    if Hardware::CPU.intel?
      url ""
      sha256 ""
    end

    def install
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        filename = File.basename("")
        bin.install filename => "salami"
      end

      if Hardware::CPU.intel?
        filename = File.basename("")
        bin.install filename => "salami"
      end
    end
  end

  test do
    system "#{bin}/salami version"
  end
end