# frozen_string_literal: true

# This file was generated by https://github.com/salami/salami/blob/master/.github/scripts/generate-homebrew-tap
class Salami < Formula
  desc "Salami - Infrastructure as Natural Language"
  homepage "https://github.com/petrgazarov/salami"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/petrgazarov/salami/releases/download/0.0.1/salami-0.0.1-darwin-x64"
      sha256 "f9425d8bf18ae18af6284f856160dac411ad293515b81a74ce76ef4f9bf8c0e6"
    end

    if Hardware::CPU.arm?
      url "https://github.com/petrgazarov/salami/releases/download/0.0.1/salami-0.0.1-darwin-arm64"
      sha256 "b77618f4c22642f25c3bfc7f3d0b462517cf46bca3215e86791176c426e69556"
    end

    def install
      if Hardware::CPU.intel?
        filename = File.basename("https://github.com/petrgazarov/salami/releases/download/0.0.1/salami-0.0.1-darwin-x64")
        bin.install filename => "salami"
      end

      if Hardware::CPU.arm?
        filename = File.basename("https://github.com/petrgazarov/salami/releases/download/0.0.1/salami-0.0.1-darwin-arm64")
        bin.install filename => "salami"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/petrgazarov/salami/releases/download/0.0.1/salami-0.0.1-linux-arm64"
      sha256 "3572f0882240db1ccca9867132909f24fc72d2139e5775212e127ba85d74f58c"
    end

    if Hardware::CPU.intel?
      url "https://github.com/petrgazarov/salami/releases/download/0.0.1/salami-0.0.1-linux-x64"
      sha256 "955952687bf5a5ce38478bf44d80f5f6d1d3c7704f513e4fe5f3f7422ea350b0"
    end

    def install
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        filename = File.basename("https://github.com/petrgazarov/salami/releases/download/0.0.1/salami-0.0.1-linux-arm64")
        bin.install filename => "salami"
      end

      if Hardware::CPU.intel?
        filename = File.basename("https://github.com/petrgazarov/salami/releases/download/0.0.1/salami-0.0.1-linux-x64")
        bin.install filename => "salami"
      end
    end
  end

  test do
    system "#{bin}/salami version"
  end
end